name: cascade-migration
base: core24
version: '0.1'
summary: Snap delivering UC24 image for brownfield upgrade
description: |
  Proof-of-concept snap to simulate a migration workflow using a UC24 image
  payload. On first run, it copies the payload into $SNAP_DATA and writes
  a config file for the external migration-agent.

grade: devel
confinement: devmode

apps:
  prepare-payload:
    command: bin/entrypoint.sh
    daemon: simple
    install-mode: disable
    plugs:
      - network
      - network-bind

parts:
  uc24-img:
    plugin: dump
    source: payloads/
    organize:
      uc24.img: payloads/uc24.img

  wrapper:
    plugin: dump
    source: snap/
    organize:
      bin/entrypoint.sh: bin/entrypoint.sh

  utils:
    plugin: nil
    stage-packages:
      - coreutils
      - bash
