name: cascade-migration
base: core24
version: '0.1'
summary: Snap delivering UC24 image for brownfield upgrade
description: |
  Proof-of-concept snap to simulate a migration workflow using a UC24 image
  payload. On install, it writes a config file to $SNAP_DATA for use by
  the migration-agent.

grade: devel
confinement: devmode

parts:
  uc24-img:
    plugin: dump
    source: payloads/
    organize:
      uc24.img: payloads/uc24.img

  config:
    plugin: dump
    source: snap/
    organize:
      migration.conf: etc/migration.conf
